<?xml version="1.0"?>
<package format="2">

  <name>mrs_sensor_info</name>
  <version>1.0.0</version>
  <description>The MRS Sensor Info package</description>

  <maintainer email="tomas.baca@fel.cvut.cz">Tomas Baca</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <depend>mrs_lib</depend>
  <depend>mrs_modules_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
